name: Xray automatic tests provisioning

on:
  #push:
  #  paths:
  #    - 'src/api/**'
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Run tests with auto provisioning
      run: |
        docker run --name testlemon itbusina/testlemon:latest -c "$(<./examples/xray/auto-xray-provisioning.yaml)" -o output.json -f xray
        docker cp testlemon:/app/output.json output.json
        docker rm testlemon

    - name: Upload test results to Xray
      shell: pwsh
      run: |
        $client_id = "${{ secrets.XRAY_CLIENT_ID }}"
        $client_secret = "${{ secrets.XRAY_CLIENT_SECRET }}"
        $jira_base_url = "${{ secrets.XRAY_JIRA_BASE_URL }}"
        $test_results = Get-Content "output.json"
        ./scripts/xray-cloud-import.ps1 -client_id $client_id -client_secret $client_secret -jira_base_url $jira_base_url -test_results $test_results
        